~gihub~ does not display this file properly, use ~emacs~ to open it.

*Notes*:
a. remote directory mount point is arbitrary and can be configured in =~/.emacs.d/cloud/config=; here I use the default value =/mnt/cloud/=
b. `hostname` stands for the host name, my host names are "kalinin" and "kolmogorov".

Main (static) files are described in [[file:README.org][README.org]]; the code dynamically creates the following files:

* Log files
** /mnt/cloud/history
kolmogorov: 10/23 13:16:44 -- 13:17:23\\
background (en/de)cryption on kolmogorov finished 13:18:49\\
kalinin: 10/23 13:38:01 -- 13:38:25\\
background (en/de)cryption on kalinin finished 13:38:26\\
background (en/de)cryption on kalinin finished 14:39:06\\
background (en/de)cryption on kalinin finished 15:38:25\\
background (en/de)cryption on kalinin finished 16:38:26\\
kalinin: 10/23 16:38:01 -- 16:38:26\\
background (en/de)cryption on kalinin finished 17:38:25\\
kalinin: 10/23 17:38:01 -- 17:38:25\\
kalinin: 10/23 17:48:57 -- 17:48:57\\
kalinin: 10/23 17:49:25 -- 17:49:51\\
background (en/de)cryption on kalinin finished 17:49:51\\
background (en/de)cryption on kalinin finished 17:52:58\\
kalinin: 10/23 17:52:33 -- 17:52:59\\
kalinin: 10/23 18:11:46 -- 18:12:11\\
background (en/de)cryption on kalinin finished 18:12:12\\
background (en/de)cryption on kalinin finished 18:14:53\\
background (en/de)cryption on kalinin finished 18:38:24\\
kalinin: 10/23 18:38:01 -- 18:38:24

** ~/.emacs.d/cloud/kalinin.log
While emacs is frozen while syncronization is not done, this file allows to see (en/de)coding operations in real time:

10/23 17:49:48: uploaded ~/cloud/cloud.org\\
10/23 17:49:46: downloaded ~/tmp2.max\\
10/23 17:49:28: downloaded ~/tmp.max\\
10/23 17:49:28: downloaded ~/tmp5.max\\
17:52:58: uploaded ~/cloud/cloud.org\\
18:12:11: uploaded ~/cloud/cloud.org\\
18:12:12: downloaded ~/tmp1.max\\
18:38:24: uploaded ~/cloud/cloud.org\\
18:38:24: uploaded ~/task.txt

** ~/.emacs.d/elisp.log
Previous log files were project-specific.
Apart from them, there is also "global" log file =~/.emacs.d/elisp.log=.
Its content is created by my [[https://github.com/chalaev/elisp-goodies][logging code]] using =(clog ...)= commands.

=clog= outputs log messages both to ~*Messages*~ buffer and to =~/.emacs.d/elisp.log=.
When the variable  =*log-level*= is set to =:info= level
#+BEGIN_SRC emacs-lisp
(defvar *log-level* 1)
#+END_SRC
in =~/.emacs=, only few log messages are output to =~/.emacs.d/elisp.log=.

To see more messages, set =*log-level*=  to =:debug= (zero) level:
#+BEGIN_SRC emacs-lisp
(setf *log-level* 0)
#+END_SRC

** =*cloud-batch*=
=*cloud-batch*= is the name of ~emacs~ buffer where GNU make output is stored.

* Other files
1. =~/.emacs.d/cloud/config= (contains gpg password – don't cloud it!) Created by the user or by the code at the very first code run.
2. [[file:cloud.mk][~/.emacs.d/cloud/cloud.mk]] is the last GNU make file created during the previous =(cloud-sync)=
3. =~/.emacs.d/cloud/individual.passes= contains individual password for *all* images, e.g.,\\
   cL2 EKPBqTxuHoo8CF4v\\
   RGq f9f0vIgxu9VOvrjc
4. Numerous =~/.emacs.d/cloud/images/???= (one per image) files contain individual image passwords.
5. =~/.emacs.d/cloud/`hostname`.log= is the host-specific log file for the `hostname`.
6. =/mnt/cloud/now-syncing/= is a lock directory; its existence tells other hosts that the cloud is busy now and they have to wait before launching =cloud-sync=.
7. =/mnt/cloud/now-syncing/`hostname`= tells the time when the =cloud-sync= on =`hostname`= started. Normally erased after =cloud-sync= has done the job.
