~gihub~ does not display this file properly; better use ~emacs~ to open it.

* Source files
1. [[file:README.org][README.org]] generates =README.md= for [[https://notabug.org/shalaev/emacs-cloud][notabug]] and [[https://github.com/chalaev/cloud][github]].
2. [[file:cloud.org][cloud.org]] contains the code from [[file:generated/main.el][generated/main.el]] together with explanations.
3. [[file:0.el][0.el]], [[file:1.el][1.el]], and [[file:2.org][2.org]] are kind of "Appendix" containing some pieces of code which not interesting enough to be included in [[file:cloud.org][cloud.org]].
4. [[file:Makefile][Makefile]] merges all the code into [[file:packaged/cloud.el][packaged/cloud.el]] which is the main file to be launched when ~emacs~ starts.
5. [[file:shell/cloud-git][shell/cloud-git]] synchronizes file operations in ~git~ with this code, for example:\\
   =cloud-git rm files.org= or =cloud-git mv log-files.org files.org=
6. [[file:shell/csed-i][shell/csed-i]] calls ~sed -i~ to update the file(s) and notifies elisp code about that.
7. [[file:testing.org][testing.org]] describes multi-scale testing procedure.
8. [[file:bugs.org][bugs.org]] contains
   a. error and problem list, and
   b. ideas on further development.

* Generated files
*Notes*:
a. remote directory mount point is arbitrary and can be configured in =~/.emacs.d/cloud/config=; here I use the default value =/mnt/cloud/=
b. `hostname` stands for the host name, my host names are "kalinin" and "kolmogorov".

** Log files
Debugging becaomes easier when we watch all the logs:
#+BEGIN_SRC shell
tail -f /mnt/cloud/history /mnt/cloud/hosts/* ~/.emacs.d/elisp.log ~/.emacs.d/cloud/pass.d/updated ~/.emacs.d/cloud/*/log ~/.emacs.d/cloud/*.log
#+END_SRC

** /mnt/cloud/history
kolmogorov: 10/23 13:16:44 -- 13:17:23\\
background (en/de)cryption on kolmogorov finished 13:18:49\\
kalinin: 10/23 13:38:01 -- 13:38:25\\
background (en/de)cryption on kalinin finished 13:38:26\\
background (en/de)cryption on kalinin finished 14:39:06\\
background (en/de)cryption on kalinin finished 15:38:25\\
background (en/de)cryption on kalinin finished 16:38:26\\
kalinin: 10/23 16:38:01 -- 16:38:26\\
background (en/de)cryption on kalinin finished 17:38:25\\
kalinin: 10/23 17:38:01 -- 17:38:25\\
kalinin: 10/23 17:48:57 -- 17:48:57\\
kalinin: 10/23 17:49:25 -- 17:49:51\\
background (en/de)cryption on kalinin finished 17:49:51\\
background (en/de)cryption on kalinin finished 17:52:58\\
kalinin: 10/23 17:52:33 -- 17:52:59\\
kalinin: 10/23 18:11:46 -- 18:12:11\\
background (en/de)cryption on kalinin finished 18:12:12\\
background (en/de)cryption on kalinin finished 18:14:53\\
background (en/de)cryption on kalinin finished 18:38:24\\
kalinin: 10/23 18:38:01 -- 18:38:24

** ~/.emacs.d/cloud/kalinin/log
While emacs is frozen while syncronization is not done, this file allows to see (en/de)coding operations in real time:

17:49:48: uploaded ~/cloud/cloud.org\\
17:49:46: downloaded ~/tmp2.max\\
17:49:28: downloaded ~/tmp.max\\
17:49:28: downloaded ~/tmp5.max\\
17:52:58: uploaded ~/cloud/cloud.org\\
18:12:11: uploaded ~/cloud/cloud.org\\
18:12:12: downloaded ~/tmp1.max\\
18:38:24: uploaded ~/cloud/cloud.org\\
18:38:24: uploaded ~/task.txt

** ~/.emacs.d/elisp.log
Previous log files were project-specific.
Apart from them, there is also "global" log file =~/.emacs.d/elisp.log=.
Its content is created by my [[https://github.com/chalaev/lisp-goodies][logging code]] using =(clog ...)= commands.

=clog= outputs log messages both to ~*Messages*~ buffer and to =~/.emacs.d/elisp.log=.
When the variable  =*log-level*= is set to =:info= level
#+BEGIN_SRC emacs-lisp
(defvar *log-level* 1)
#+END_SRC
in =~/.emacs=, only few log messages are output to =~/.emacs.d/elisp.log=.

To see more messages, set =*log-level*=  to =:debug= (zero) level:
#+BEGIN_SRC emacs-lisp
(setf *log-level* 0)
#+END_SRC

** Test logs
Three files tests/{[[file:tests/micro.log][micro]],[[file:tests/meso.log][meso]],[[file:tests/macro-0.log][macro-0]],[[file:tests/macro-1.log][macro-1]],[[file:tests/macro-2.log][macro-2]]}.log contain output from [[file:testing.org][multi-scaled testing]].
The directory [[file:tests/][tests/]] can be safely removed (e.g., by =make clean=); all files there will be re-generated by =make=.

** Other files
1. [[file:config][~/.emacs.d/cloud/`hostname`/config]] (contains gpg password – don't cloud it!) Created by the user or by the code at the very first code run.
2. [[file:make-files/1.mk][~/.emacs.d/cloud/cloud.mk]] is the last GNU make file created during the previous =(cloud-sync)=
3. =~/.emacs.d/cloud/individual.passes= contains individual password for *all* images, e.g.,\\
   cL2 EKPBqTxuHoo8CF4v
   RGq f9f0vIgxu9VOvrjc
4. Numerous =~/.emacs.d/cloud/images/???= (temporary, one per image) files contain individual image passwords.
5. =/mnt/cloud/now-syncing/= is a lock directory; its existence tells other hosts that the cloud is busy now and they have to wait before launching their =cloud-sync=.
6. =/mnt/cloud/now-syncing/`hostname`= tells the time when the =cloud-sync= on =`hostname`= started. Normally erased after =cloud-sync= has done the job.
