Intended for linux users who have [[https://www.gnu.org/software/emacs/][emacs]] always open.

I did not expect this project to grow that much;
some of the desired functions are still not implemented or half-implemented.

* Description
Synchronizing important files on two or more computers using
1. ~emacs~ + GNU ~make~,
2. some sort of a cloud that can be mounted to a directory, for example, an
   a. ssh-server, or
   b. some public cloud service (e.g., Russian [[https://disk.yandex.com/][Yandex Disk]] or Swiss [[https://www.pcloud.com][pCloud]]) that can be mounted in linux
      using standard open-source utilities,
   and
3. symmetric encryption
   a. using [[https://imagemagick.org/][ImageMagick]] for ~JPEG~ and ~PNG~ images or
   b. using [[https://www.gnupg.org/][gpg]] for other (presumably text) files.
   ~JPEGs~ and ~PNGs~ are encrypted with AES-algorithm that [[https://imagemagick.org/script/cipher.php][may become vulnerable]] if the same password is used for multiple images; this is why every image gets an individual password.

Encrypted files saved in the cloud have *random names* to minimize the amount of information Evil Corporations can extract by monitoring our cloud directory.

* Prerequisites
We need ~emacs~, GNU ~make~, ~ImageMagick~, ~gpg~ and ~gawk~; in Debian these can be installed with ~aptitude~ as follows:
#+BEGIN_SRC shell
aptitude install emacs make imagemagick gpg gawk
#+END_SRC

* Quick start
I am running emacs in daemon mode (in text console) with the following =~/.bash_login=
#+BEGIN_SRC shell
(emacs --daemon ; make -j8 -f ~/.emacs.d/cloud/cloud.mk all) &
#+END_SRC
and =~/.bash_logout=
#+BEGIN_SRC shell
emacsclient -e "(kill-emacs)"
#+END_SRC
where in =~/.bash_login= I assumed that there are 8 CPU cores available.
The I use =emacsclient -c= to open a new (gui) emacs window.

1. Mount remote directory. The mounting point may be arbitrary (specified as =cloud-directory= in =~/.emacs.d/cloud/config=), the default one is ~/mnt/cloud/~.
2. You can create the file =~/.emacs.d/cloud/config= yourself, or it will be generated. Mine looks as follows:
   #+BEGIN_SRC
   delete-contents=yes
   contents-name=XYZ
   password=*********
   number-of-CPU-cores=8
   cloud-directory=/mnt/lws/cloud/
   #+END_SRC
3. Evaluate ~cloud.el~ in ~emacs~ at start by placing the following lines
   #+BEGIN_SRC emacs-lisp
   (server-start)
   (mapcar #'require '(cl dired-aux timezone diary-lib subr-x))
   (load-file "/path-to/cloud.el")
   (switch-to-buffer "*Messages*")
   (cloud-start)
   #+END_SRC
   into your =~/.emacs= file.
   Then open a directory =C-x d=, mark several files, and cloud them with =M-x cloud-add=. Then =M-x cloud-sync=.
4. Check log files described in [[file:files.org][files.org]]: they should let you know that the encrypted copies of your clouded files have been copied to the remote directory
5. Using some secure way, copy =~/.emacs.d/cloud/config= to another host; launch ~cloud.el~ there and check the log files.
6. [[https://github.com/chalaev/cloud/issues/new/choose][Let me know]] if something does not work.

Every time we =M-x cloud-sync=, local files get synchronized with the cloud. For this purpose I have a line in my ~crontab~:
=43 9-21 * * * emacsclient -e "(cloud-sync)" &> /dev/null=

* Source code files
(Dynamically created/updated logs and data files are described in [[file:files.org][files.org]].)
1. [[file:README.org][README.org]] generates =README.md= for [[https://notabug.org/shalaev/emacs-cloud][notabug]] and [[https://github.com/chalaev/cloud][github]].
2. [[file:cloud.org][cloud.org]] contains the code from [[file:generated/main.el][generated/main.el]] together with explanations.
3. [[file:0.el][0.el]], [[file:1.el][1.el]], and [[file:2.el][2.el]] are kind of "Appendix" containing some pieces of code which not interesting enough to be included in ~cloud.org~.
4. goodies/{[[file:goodies/macros.el][macros]],[[file:goodies/functions.el][functions]],[[file:goodies/logging.el][logging]]}.el are copied from the [[https://notabug.org/shalaev/elisp-goodies][elisp-goodies]] project.
5. [[file:Makefile][Makefile]] merges all the code into [[file:generated/cloud.el][generated/cloud.el]] which is the main file to be launched when ~emacs~ starts.
6. [[file:shell/cloud-git][shell/cloud-git]] synchronizes file operations in ~git~ with this code, for example:
   =cloud-git rm files.org= and =cloud-git mv log-files.org files.org=
7. [[file:bugs.org][bugs.org]] contains
   a. error and problem list,
   b. tests to be done, and
   c. ideas on further development.

* Motivation
I like cloud file storages: they are cheap (or even free) and reliable.

However, Evil Corporations and governments are trying to spy on people using the information
that they extract from private data stored in the cloud.

Most of my important files (for example, emails or document scans) are not regularly changed;
for those I use [[https://github.com/gkiefer/backup2l][backup2l]] with gpg encryption, and store encrypted archives
using one of cloud services that allow ~WebDav~ access to the storage directory (Russian [[https://disk.yandex.com/][Yandex Disk]] or Swiss [[https://www.pcloud.com][pCloud]]).

This does not work so well for regularly changed files.
Since emacs is my only text editor, it is enough to write eLisp code that
1. Saves unencrypted file locally and its encrypted copy in the cloud.
2. Every file in =dired= buffer can be "clouded" (=M-x cloud-add=).
3. Encrypted files are stored under randomly generated names and modification dates/times.
4. Remotely stored files are periodically syncronized with the local ones.
5. Dired-compatible: whatever I do with a file in dired (delete, rename), will be automatically done on other computers.

* Limitations
1. I use [[https://www.gnu.org/software/make/][GNU make]] together with its =--jobs= option to enjoy [[https://www.emacswiki.org/emacs/EmacsLispLimitations][(unsupported in emacs)]] multi-threading, and thus
   I have to suffer from the [[https://www.gnu.org/software/make/][make]] restriction: only nicely named files will work.\\
   In particular, *no spaces in file names* are allowed.\\
   In the future I hope to circumvent this limitation by creating soft links to badly named files.
2. After encrypting an image and then decrypting it back, we get the same, but not identical picture (file size is changed).

* Support
You can support this project by sending
1. comments/questions to [[mailto:oleg@chalaev.com][oleg@chalaev.com]] and
2. donations via [[https://liberapay.com/shalaev/donate][liberapay]] or [[https://www.paypal.com/paypalme/chalaev][paypal]].
